// Code generated by sky-ffi-inspect from bufio. DO NOT EDIT.
// Re-run `sky add bufio` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Bufio as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "bufio"
	"fmt"
	io "io"
	_ "reflect"
)

type FfiT_Go_Bufio_newReadWriter_P0 = *pkg.Reader
type FfiT_Go_Bufio_newReadWriter_P1 = *pkg.Writer
type FfiT_Go_Bufio_newReadWriter_R = *pkg.ReadWriter

type FfiT_Go_Bufio_newReader_P0 = io.Reader
type FfiT_Go_Bufio_newReader_R = *pkg.Reader

type FfiT_Go_Bufio_newReaderSize_P0 = io.Reader
type FfiT_Go_Bufio_newReaderSize_R = *pkg.Reader

type FfiT_Go_Bufio_newScanner_P0 = io.Reader
type FfiT_Go_Bufio_newScanner_R = *pkg.Scanner
// [pure] typed wrapper for Go_Bufio_newScanner (P7 adaptor target)
func Go_Bufio_newScannerT(arg0 io.Reader) (out SkyResult[any, *pkg.Scanner]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,*pkg.Scanner](pkg.NewScanner(arg0))
	return
}

type FfiT_Go_Bufio_newWriter_P0 = io.Writer
type FfiT_Go_Bufio_newWriter_R = *pkg.Writer

type FfiT_Go_Bufio_newWriterSize_P0 = io.Writer
type FfiT_Go_Bufio_newWriterSize_R = *pkg.Writer

type FfiT_Go_Bufio_readWriterAvailable_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterAvailableBuffer_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterDiscard_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterFlush_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterPeek_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterRead_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadByte_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadBytes_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadFrom_P0 = *pkg.ReadWriter
type FfiT_Go_Bufio_readWriterReadFrom_P1 = io.Reader

type FfiT_Go_Bufio_readWriterReadLine_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadRune_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadSlice_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterReadString_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterUnreadByte_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterUnreadRune_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWrite_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWriteByte_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWriteRune_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWriteString_P0 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWriteTo_P0 = *pkg.ReadWriter
type FfiT_Go_Bufio_readWriterWriteTo_P1 = io.Writer

type FfiT_Go_Bufio_readWriterReader_P0 = *pkg.ReadWriter
type FfiT_Go_Bufio_readWriterReader_R = *pkg.Reader

type FfiT_Go_Bufio_readWriterSetReader_P0 = pkg.Reader
type FfiT_Go_Bufio_readWriterSetReader_P1 = *pkg.ReadWriter

type FfiT_Go_Bufio_readWriterWriter_P0 = *pkg.ReadWriter
type FfiT_Go_Bufio_readWriterWriter_R = *pkg.Writer

type FfiT_Go_Bufio_readWriterSetWriter_P0 = pkg.Writer
type FfiT_Go_Bufio_readWriterSetWriter_P1 = *pkg.ReadWriter

type FfiT_Go_Bufio_readerSize_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReset_P0 = *pkg.Reader
type FfiT_Go_Bufio_readerReset_P1 = io.Reader

type FfiT_Go_Bufio_readerPeek_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerDiscard_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerRead_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadByte_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerUnreadByte_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadRune_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerUnreadRune_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerBuffered_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadSlice_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadLine_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadBytes_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerReadString_P0 = *pkg.Reader

type FfiT_Go_Bufio_readerWriteTo_P0 = *pkg.Reader
type FfiT_Go_Bufio_readerWriteTo_P1 = io.Writer

type FfiT_Go_Bufio_scannerErr_P0 = *pkg.Scanner

type FfiT_Go_Bufio_scannerBytes_P0 = *pkg.Scanner

type FfiT_Go_Bufio_scannerText_P0 = *pkg.Scanner
// [pure] typed wrapper for Go_Bufio_scannerText (P7 adaptor target)
func Go_Bufio_scannerTextT(arg0 *pkg.Scanner) (out SkyResult[any, string]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,string](ErrFfi("nil receiver: Scanner.Text")); return }
	out = Ok[any,string](arg0.Text())
	return
}

type FfiT_Go_Bufio_scannerScan_P0 = *pkg.Scanner
// [pure] typed wrapper for Go_Bufio_scannerScan (P7 adaptor target)
func Go_Bufio_scannerScanT(arg0 *pkg.Scanner) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,bool](ErrFfi("nil receiver: Scanner.Scan")); return }
	out = Ok[any,bool](arg0.Scan())
	return
}

type FfiT_Go_Bufio_scannerBuffer_P0 = *pkg.Scanner

type FfiT_Go_Bufio_scannerSplit_P0 = *pkg.Scanner
type FfiT_Go_Bufio_scannerSplit_P1 = pkg.SplitFunc

type FfiT_Go_Bufio_writerSize_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerReset_P0 = *pkg.Writer
type FfiT_Go_Bufio_writerReset_P1 = io.Writer

type FfiT_Go_Bufio_writerFlush_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerAvailable_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerAvailableBuffer_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerBuffered_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerWrite_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerWriteByte_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerWriteRune_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerWriteString_P0 = *pkg.Writer

type FfiT_Go_Bufio_writerReadFrom_P0 = *pkg.Writer
type FfiT_Go_Bufio_writerReadFrom_P1 = io.Reader


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
