// Code generated by sky-ffi-inspect from os/exec. DO NOT EDIT.
// Re-run `sky add os/exec` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Os.Exec as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "os/exec"
	"fmt"
	context "context"
	io "io"
	os "os"
	time "time"
	_ "reflect"
)

type FfiT_Go_Exec_cmdString_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdRun_P0 = *pkg.Cmd
// [fallible] typed wrapper for Go_Exec_cmdRun (P7 adaptor target)
func Go_Exec_cmdRunT(arg0 *pkg.Cmd) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Cmd.Run")); return }
	err := arg0.Run()
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Exec_cmdStart_P0 = *pkg.Cmd
// [fallible] typed wrapper for Go_Exec_cmdStart (P7 adaptor target)
func Go_Exec_cmdStartT(arg0 *pkg.Cmd) (out SkyResult[any, struct{}]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,struct{}](ErrFfi("nil receiver: Cmd.Start")); return }
	err := arg0.Start()
	if err != nil { out = Err[any,struct{}](ErrFfi(err.Error())); return }
	out = Ok[any,struct{}](struct{}{})
	return
}

type FfiT_Go_Exec_cmdWait_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdOutput_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdCombinedOutput_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdStdinPipe_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStdinPipe_R = io.WriteCloser

type FfiT_Go_Exec_cmdStdoutPipe_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStdoutPipe_R = io.ReadCloser
// [fallible] typed wrapper for Go_Exec_cmdStdoutPipe (P7 adaptor target)
func Go_Exec_cmdStdoutPipeT(arg0 *pkg.Cmd) (out SkyResult[any, io.ReadCloser]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,io.ReadCloser](ErrFfi("nil receiver: Cmd.StdoutPipe")); return }
	r0, err := arg0.StdoutPipe()
	if err != nil { out = Err[any,io.ReadCloser](ErrFfi(err.Error())); return }
	out = Ok[any,io.ReadCloser](r0)
	return
}

type FfiT_Go_Exec_cmdStderrPipe_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStderrPipe_R = io.ReadCloser

type FfiT_Go_Exec_cmdEnviron_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdPath_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetPath_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdArgs_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetArgs_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdEnv_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetEnv_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdDir_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetDir_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdStdin_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStdin_R = io.Reader

type FfiT_Go_Exec_cmdSetStdin_P0 = io.Reader
type FfiT_Go_Exec_cmdSetStdin_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdStdout_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStdout_R = io.Writer

type FfiT_Go_Exec_cmdSetStdout_P0 = io.Writer
type FfiT_Go_Exec_cmdSetStdout_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdStderr_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdStderr_R = io.Writer

type FfiT_Go_Exec_cmdSetStderr_P0 = io.Writer
type FfiT_Go_Exec_cmdSetStderr_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdExtraFiles_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdExtraFiles_R = []*os.File

type FfiT_Go_Exec_cmdSetExtraFiles_P0 = []*os.File
type FfiT_Go_Exec_cmdSetExtraFiles_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdSysProcAttr_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdProcess_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdProcess_R = *os.Process

type FfiT_Go_Exec_cmdSetProcess_P0 = os.Process
type FfiT_Go_Exec_cmdSetProcess_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdProcessState_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdProcessState_R = *os.ProcessState

type FfiT_Go_Exec_cmdSetProcessState_P0 = os.ProcessState
type FfiT_Go_Exec_cmdSetProcessState_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdErr_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetErr_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdCancel_P0 = *pkg.Cmd

type FfiT_Go_Exec_cmdSetCancel_P1 = *pkg.Cmd

type FfiT_Go_Exec_cmdWaitDelay_P0 = *pkg.Cmd
type FfiT_Go_Exec_cmdWaitDelay_R = time.Duration

type FfiT_Go_Exec_cmdSetWaitDelay_P0 = time.Duration
type FfiT_Go_Exec_cmdSetWaitDelay_P1 = *pkg.Cmd

type FfiT_Go_Exec_command_R = *pkg.Cmd
// [pure] typed wrapper for Go_Exec_command (P7 adaptor target)
func Go_Exec_commandT(arg0 string, arg1 []string) (out SkyResult[any, *pkg.Cmd]) {
	defer SkyFfiRecoverT(&out)()
	out = Ok[any,*pkg.Cmd](pkg.Command(arg0, arg1...))
	return
}

type FfiT_Go_Exec_commandContext_P0 = context.Context
type FfiT_Go_Exec_commandContext_R = *pkg.Cmd

type FfiT_Go_Exec_errorError_P0 = *pkg.Error

type FfiT_Go_Exec_errorUnwrap_P0 = *pkg.Error

type FfiT_Go_Exec_errorName_P0 = *pkg.Error

type FfiT_Go_Exec_errorSetName_P1 = *pkg.Error

type FfiT_Go_Exec_errorErr_P0 = *pkg.Error

type FfiT_Go_Exec_errorSetErr_P1 = *pkg.Error

type FfiT_Go_Exec_exitErrorError_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorExitCode_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorExited_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorPid_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorString_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorSuccess_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorSys_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorSysUsage_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorSystemTime_P0 = *pkg.ExitError
type FfiT_Go_Exec_exitErrorSystemTime_R = time.Duration

type FfiT_Go_Exec_exitErrorUserTime_P0 = *pkg.ExitError
type FfiT_Go_Exec_exitErrorUserTime_R = time.Duration

type FfiT_Go_Exec_exitErrorProcessState_P0 = *pkg.ExitError
type FfiT_Go_Exec_exitErrorProcessState_R = *os.ProcessState

type FfiT_Go_Exec_exitErrorSetProcessState_P0 = os.ProcessState
type FfiT_Go_Exec_exitErrorSetProcessState_P1 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorStderr_P0 = *pkg.ExitError

type FfiT_Go_Exec_exitErrorSetStderr_P1 = *pkg.ExitError


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
