// Code generated by sky-ffi-inspect from os. DO NOT EDIT.
// Re-run `sky add os` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Os as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "os"
	"fmt"
	io "io"
	fs "io/fs"
	time "time"
	_ "reflect"
)

type FfiT_Go_Os_chmod_P1 = pkg.FileMode

type FfiT_Go_Os_chtimes_P1 = time.Time
type FfiT_Go_Os_chtimes_P2 = time.Time

type FfiT_Go_Os_copyFS_P1 = fs.FS

type FfiT_Go_Os_create_R = *pkg.File

type FfiT_Go_Os_createTemp_R = *pkg.File

type FfiT_Go_Os_dirFS_R = fs.FS

type FfiT_Go_Os_fileReaddir_P0 = *pkg.File
type FfiT_Go_Os_fileReaddir_R = []pkg.FileInfo

type FfiT_Go_Os_fileReaddirnames_P0 = *pkg.File

type FfiT_Go_Os_fileReadDir_P0 = *pkg.File
type FfiT_Go_Os_fileReadDir_R = []pkg.DirEntry

type FfiT_Go_Os_fileName_P0 = *pkg.File

type FfiT_Go_Os_fileRead_P0 = *pkg.File

type FfiT_Go_Os_fileReadAt_P0 = *pkg.File

type FfiT_Go_Os_fileReadFrom_P0 = *pkg.File
type FfiT_Go_Os_fileReadFrom_P1 = io.Reader

type FfiT_Go_Os_fileWrite_P0 = *pkg.File

type FfiT_Go_Os_fileWriteAt_P0 = *pkg.File

type FfiT_Go_Os_fileWriteTo_P0 = *pkg.File
type FfiT_Go_Os_fileWriteTo_P1 = io.Writer

type FfiT_Go_Os_fileSeek_P0 = *pkg.File

type FfiT_Go_Os_fileWriteString_P0 = *pkg.File
// [fallible] typed wrapper for Go_Os_fileWriteString (P7 adaptor target)
func Go_Os_fileWriteStringT(arg0 *pkg.File, arg1 string) (out SkyResult[any, int]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,int](ErrFfi("nil receiver: File.WriteString")); return }
	r0, err := arg0.WriteString(arg1)
	if err != nil { out = Err[any,int](ErrFfi(err.Error())); return }
	out = Ok[any,int](r0)
	return
}

type FfiT_Go_Os_fileChmod_P0 = *pkg.File
type FfiT_Go_Os_fileChmod_P1 = pkg.FileMode

type FfiT_Go_Os_fileSetDeadline_P0 = *pkg.File
type FfiT_Go_Os_fileSetDeadline_P1 = time.Time

type FfiT_Go_Os_fileSetReadDeadline_P0 = *pkg.File
type FfiT_Go_Os_fileSetReadDeadline_P1 = time.Time

type FfiT_Go_Os_fileSetWriteDeadline_P0 = *pkg.File
type FfiT_Go_Os_fileSetWriteDeadline_P1 = time.Time

type FfiT_Go_Os_fileFd_P0 = *pkg.File

type FfiT_Go_Os_fileClose_P0 = *pkg.File

type FfiT_Go_Os_fileChown_P0 = *pkg.File

type FfiT_Go_Os_fileTruncate_P0 = *pkg.File

type FfiT_Go_Os_fileSync_P0 = *pkg.File

type FfiT_Go_Os_fileChdir_P0 = *pkg.File

type FfiT_Go_Os_fileStat_P0 = *pkg.File
type FfiT_Go_Os_fileStat_R = pkg.FileInfo

type FfiT_Go_Os_findProcess_R = *pkg.Process

type FfiT_Go_Os_linkErrorError_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorUnwrap_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorOp_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorSetOp_P1 = *pkg.LinkError

type FfiT_Go_Os_linkErrorOld_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorSetOld_P1 = *pkg.LinkError

type FfiT_Go_Os_linkErrorNew_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorSetNew_P1 = *pkg.LinkError

type FfiT_Go_Os_linkErrorErr_P0 = *pkg.LinkError

type FfiT_Go_Os_linkErrorSetErr_P1 = *pkg.LinkError

type FfiT_Go_Os_lstat_R = pkg.FileInfo

type FfiT_Go_Os_mkdir_P1 = pkg.FileMode

type FfiT_Go_Os_mkdirAll_P1 = pkg.FileMode

type FfiT_Go_Os_newFile_R = *pkg.File

type FfiT_Go_Os_open_R = *pkg.File

type FfiT_Go_Os_openFile_P2 = pkg.FileMode
type FfiT_Go_Os_openFile_R = *pkg.File

type FfiT_Go_Os_openInRoot_R = *pkg.File

type FfiT_Go_Os_openRoot_R = *pkg.Root

type FfiT_Go_Os_procAttrDir_P0 = *pkg.ProcAttr

type FfiT_Go_Os_procAttrSetDir_P1 = *pkg.ProcAttr

type FfiT_Go_Os_procAttrEnv_P0 = *pkg.ProcAttr

type FfiT_Go_Os_procAttrSetEnv_P1 = *pkg.ProcAttr

type FfiT_Go_Os_procAttrFiles_P0 = *pkg.ProcAttr
type FfiT_Go_Os_procAttrFiles_R = []*pkg.File

type FfiT_Go_Os_procAttrSetFiles_P0 = []*pkg.File
type FfiT_Go_Os_procAttrSetFiles_P1 = *pkg.ProcAttr

type FfiT_Go_Os_procAttrSys_P0 = *pkg.ProcAttr

type FfiT_Go_Os_processRelease_P0 = *pkg.Process

type FfiT_Go_Os_processKill_P0 = *pkg.Process

type FfiT_Go_Os_processWait_P0 = *pkg.Process
type FfiT_Go_Os_processWait_R = *pkg.ProcessState

type FfiT_Go_Os_processSignal_P0 = *pkg.Process
type FfiT_Go_Os_processSignal_P1 = pkg.Signal

type FfiT_Go_Os_processWithHandle_P0 = *pkg.Process

type FfiT_Go_Os_processPid_P0 = *pkg.Process

type FfiT_Go_Os_processSetPid_P1 = *pkg.Process

type FfiT_Go_Os_processStateUserTime_P0 = *pkg.ProcessState
type FfiT_Go_Os_processStateUserTime_R = time.Duration

type FfiT_Go_Os_processStateSystemTime_P0 = *pkg.ProcessState
type FfiT_Go_Os_processStateSystemTime_R = time.Duration

type FfiT_Go_Os_processStateExited_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStateSuccess_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStateSys_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStateSysUsage_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStatePid_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStateString_P0 = *pkg.ProcessState

type FfiT_Go_Os_processStateExitCode_P0 = *pkg.ProcessState

type FfiT_Go_Os_readDir_R = []pkg.DirEntry

type FfiT_Go_Os_rootName_P0 = *pkg.Root

type FfiT_Go_Os_rootClose_P0 = *pkg.Root

type FfiT_Go_Os_rootOpen_P0 = *pkg.Root
type FfiT_Go_Os_rootOpen_R = *pkg.File

type FfiT_Go_Os_rootCreate_P0 = *pkg.Root
type FfiT_Go_Os_rootCreate_R = *pkg.File

type FfiT_Go_Os_rootOpenFile_P0 = *pkg.Root
type FfiT_Go_Os_rootOpenFile_P3 = pkg.FileMode
type FfiT_Go_Os_rootOpenFile_R = *pkg.File

type FfiT_Go_Os_rootOpenRoot_P0 = *pkg.Root
type FfiT_Go_Os_rootOpenRoot_R = *pkg.Root

type FfiT_Go_Os_rootChmod_P0 = *pkg.Root
type FfiT_Go_Os_rootChmod_P2 = pkg.FileMode

type FfiT_Go_Os_rootMkdir_P0 = *pkg.Root
type FfiT_Go_Os_rootMkdir_P2 = pkg.FileMode

type FfiT_Go_Os_rootMkdirAll_P0 = *pkg.Root
type FfiT_Go_Os_rootMkdirAll_P2 = pkg.FileMode

type FfiT_Go_Os_rootChown_P0 = *pkg.Root

type FfiT_Go_Os_rootLchown_P0 = *pkg.Root

type FfiT_Go_Os_rootChtimes_P0 = *pkg.Root
type FfiT_Go_Os_rootChtimes_P2 = time.Time
type FfiT_Go_Os_rootChtimes_P3 = time.Time

type FfiT_Go_Os_rootRemove_P0 = *pkg.Root

type FfiT_Go_Os_rootRemoveAll_P0 = *pkg.Root

type FfiT_Go_Os_rootStat_P0 = *pkg.Root
type FfiT_Go_Os_rootStat_R = pkg.FileInfo

type FfiT_Go_Os_rootLstat_P0 = *pkg.Root
type FfiT_Go_Os_rootLstat_R = pkg.FileInfo

type FfiT_Go_Os_rootReadlink_P0 = *pkg.Root

type FfiT_Go_Os_rootRename_P0 = *pkg.Root

type FfiT_Go_Os_rootLink_P0 = *pkg.Root

type FfiT_Go_Os_rootSymlink_P0 = *pkg.Root

type FfiT_Go_Os_rootReadFile_P0 = *pkg.Root

type FfiT_Go_Os_rootWriteFile_P0 = *pkg.Root
type FfiT_Go_Os_rootWriteFile_P3 = pkg.FileMode

type FfiT_Go_Os_rootFS_P0 = *pkg.Root
type FfiT_Go_Os_rootFS_R = fs.FS

type FfiT_Go_Os_sameFile_P0 = pkg.FileInfo
type FfiT_Go_Os_sameFile_P1 = pkg.FileInfo

type FfiT_Go_Os_signalSignal_P0 = pkg.Signal

type FfiT_Go_Os_signalString_P0 = pkg.Signal

type FfiT_Go_Os_startProcess_P2 = *pkg.ProcAttr
type FfiT_Go_Os_startProcess_R = *pkg.Process

type FfiT_Go_Os_stat_R = pkg.FileInfo

func Go_Os_stderr(_ any) any { return Ok[any, any](pkg.Stderr) }

func Go_Os_stdin(_ any) any { return Ok[any, any](pkg.Stdin) }

type FfiT_Go_Os_syscallErrorError_P0 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorUnwrap_P0 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorTimeout_P0 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorSyscall_P0 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorSetSyscall_P1 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorErr_P0 = *pkg.SyscallError

type FfiT_Go_Os_syscallErrorSetErr_P1 = *pkg.SyscallError

type FfiT_Go_Os_writeFile_P2 = pkg.FileMode


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
