// Code generated by sky-ffi-inspect from regexp. DO NOT EDIT.
// Re-run `sky add regexp` to regenerate.
//
// Wrapper functions are in `package rt` with names <Kernel>_<lowerFn>.
// Sky source resolves `import Regexp as X` and calls `X.<lowerFn>` — the canonicaliser routes it via
// the FFI registry to these typed Go functions. Every wrapper wraps
// panics in Err[any, any] via SkyFfiRecover.

package rt

import (
	pkg "regexp"
	"fmt"
	io "io"
)

type FfiT_Go_Regexp_compile_R = *pkg.Regexp
// [fallible] typed wrapper for Go_Regexp_compile (P7 adaptor target)
func Go_Regexp_compileT(arg0 string) (out SkyResult[any, *pkg.Regexp]) {
	defer SkyFfiRecoverT(&out)()
	r0, err := pkg.Compile(arg0)
	if err != nil { out = Err[any,*pkg.Regexp](ErrFfi(err.Error())); return }
	out = Ok[any,*pkg.Regexp](r0)
	return
}

type FfiT_Go_Regexp_compilePOSIX_R = *pkg.Regexp

type FfiT_Go_Regexp_matchReader_P1 = io.RuneReader

type FfiT_Go_Regexp_mustCompile_R = *pkg.Regexp

type FfiT_Go_Regexp_mustCompilePOSIX_R = *pkg.Regexp

type FfiT_Go_Regexp_regexpString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpCopy_P0 = *pkg.Regexp
type FfiT_Go_Regexp_regexpCopy_R = *pkg.Regexp

type FfiT_Go_Regexp_regexpLongest_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpNumSubexp_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpSubexpNames_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpSubexpIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpLiteralPrefix_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpMatchReader_P0 = *pkg.Regexp
type FfiT_Go_Regexp_regexpMatchReader_P1 = io.RuneReader

type FfiT_Go_Regexp_regexpMatchString_P0 = *pkg.Regexp
// [pure] typed wrapper for Go_Regexp_regexpMatchString (P7 adaptor target)
func Go_Regexp_regexpMatchStringT(arg0 *pkg.Regexp, arg1 string) (out SkyResult[any, bool]) {
	defer SkyFfiRecoverT(&out)()
	if arg0 == nil { out = Err[any,bool](ErrFfi("nil receiver: Regexp.MatchString")); return }
	out = Ok[any,bool](arg0.MatchString(arg1))
	return
}

type FfiT_Go_Regexp_regexpMatch_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpReplaceAllString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpReplaceAllLiteralString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpReplaceAllStringFunc_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpReplaceAll_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpReplaceAllLiteral_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFind_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindStringIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindReaderIndex_P0 = *pkg.Regexp
type FfiT_Go_Regexp_regexpFindReaderIndex_P1 = io.RuneReader

type FfiT_Go_Regexp_regexpFindSubmatch_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpExpand_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpExpandString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindSubmatchIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindStringSubmatch_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindStringSubmatchIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindReaderSubmatchIndex_P0 = *pkg.Regexp
type FfiT_Go_Regexp_regexpFindReaderSubmatchIndex_P1 = io.RuneReader

type FfiT_Go_Regexp_regexpFindAll_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllString_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllStringIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllSubmatch_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllSubmatchIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllStringSubmatch_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpFindAllStringSubmatchIndex_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpSplit_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpAppendText_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpMarshalText_P0 = *pkg.Regexp

type FfiT_Go_Regexp_regexpUnmarshalText_P0 = *pkg.Regexp


// Pin fmt against "imported and not used" across partial files.
var _ = fmt.Sprintf
