package main

import (
	bufio "bufio"
	_ffi_fmt "fmt"
	"io"
	_ffi_reflect "reflect"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_bufio_NewReadWriter(arg0 any, arg1 any) any {
	_arg0 := func() *bufio.Reader {
		if arg0 == nil {
			return nil
		}
		return arg0.(*bufio.Reader)
	}()
	_arg1 := func() *bufio.Writer {
		if arg1 == nil {
			return nil
		}
		return arg1.(*bufio.Writer)
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewReadWriter(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_bufio_NewReader(arg0 any) any {
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewReader(_arg0)
		return SkyOk(result)
	}()
}

func Sky_bufio_NewReaderSize(arg0 any, arg1 any) any {
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewReaderSize(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_bufio_NewScanner(arg0 any) any {
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewScanner(_arg0)
		return SkyOk(result)
	}()
}

func Sky_bufio_NewWriter(arg0 any) any {
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewWriter(_arg0)
		return SkyOk(result)
	}()
}

func Sky_bufio_NewWriterSize(arg0 any, arg1 any) any {
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := bufio.NewWriterSize(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterAvailable(receiver any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Available()
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterAvailableBuffer(receiver any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.AvailableBuffer()
		return SkyOk(result[:])
	}()
}

func Sky_bufio_ReadWriterDiscard(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Discard(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterFlush(receiver any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Flush()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReadWriterPeek(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Peek(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterRead(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Read(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterReadFrom(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadFrom(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterUnreadByte(receiver any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.UnreadByte()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReadWriterUnreadRune(receiver any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.UnreadRune()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReadWriterWrite(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Write(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterWriteString(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteString(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReadWriterWriteTo(receiver any, arg0 any) any {
	var _receiver *bufio.ReadWriter
	if _p, ok := receiver.(*bufio.ReadWriter); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.ReadWriter); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ReadWriter")
	}
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteTo(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderBuffered(receiver any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Buffered()
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderDiscard(receiver any, arg0 any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Discard(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderPeek(receiver any, arg0 any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Peek(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderRead(receiver any, arg0 any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Read(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderReset(receiver any, arg0 any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Reset(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReaderSize(receiver any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_bufio_ReaderUnreadByte(receiver any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.UnreadByte()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReaderUnreadRune(receiver any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.UnreadRune()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ReaderWriteTo(receiver any, arg0 any) any {
	var _receiver *bufio.Reader
	if _p, ok := receiver.(*bufio.Reader); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Reader); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Reader")
	}
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteTo(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_ScannerBuffer(receiver any, arg0 any, arg1 any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Buffer(_arg0, _arg1)
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ScannerBytes(receiver any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Bytes()
		return SkyOk(result[:])
	}()
}

func Sky_bufio_ScannerErr(receiver any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Err()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ScannerScan(receiver any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Scan()
		return SkyOk(result)
	}()
}

func Sky_bufio_ScannerSplit(receiver any, arg0 any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	_arg0 := func() bufio.SplitFunc {
		if v, ok := arg0.(bufio.SplitFunc); ok {
			return v
		}
		var zero bufio.SplitFunc
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Split(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_ScannerText(receiver any) any {
	var _receiver *bufio.Scanner
	if _p, ok := receiver.(*bufio.Scanner); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Scanner); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Scanner")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Text()
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterAvailable(receiver any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Available()
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterAvailableBuffer(receiver any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.AvailableBuffer()
		return SkyOk(result[:])
	}()
}

func Sky_bufio_WriterBuffered(receiver any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Buffered()
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterFlush(receiver any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Flush()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_WriterReadFrom(receiver any, arg0 any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadFrom(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterReset(receiver any, arg0 any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Reset(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_bufio_WriterSize(receiver any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Size()
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterWrite(receiver any, arg0 any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Write(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_WriterWriteString(receiver any, arg0 any) any {
	var _receiver *bufio.Writer
	if _p, ok := receiver.(*bufio.Writer); ok {
		_receiver = _p
	} else if _v, ok := receiver.(bufio.Writer); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Writer")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteString(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_bufio_FIELD_ReadWriter_Reader(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Reader")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}

func Sky_bufio_FIELD_ReadWriter_Writer(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Writer")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}
