package main

import (
	_ffi_fmt "fmt"
	os "os"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_os_FileWrite(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Write(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileWriteString(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteString(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Stderr(_ any) any {
	return os.Stderr
}

func Sky_os_Stdin(_ any) any {
	return os.Stdin
}
