package main

import (
	_ffi_fmt "fmt"
	"io"
	"io/fs"
	os "os"
	"syscall"
	"time"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_os_Chdir(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Chdir(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Chmod(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Chmod(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Chown(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := sky_asInt(arg2)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Chown(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Clearenv() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		os.Clearenv()
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Create(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Create(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_CreateTemp(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.CreateTemp(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Environ() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Environ()
		return SkyOk(result[:])
	}()
}

func Sky_os_Executable() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Executable()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Exit(arg0 any) any {
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		os.Exit(_arg0)
		return SkyOk(struct{}{})
	}()
}

func Sky_os_ExpandEnv(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.ExpandEnv(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_FindProcess(arg0 any) any {
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.FindProcess(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Getegid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getegid()
		return SkyOk(result)
	}()
}

func Sky_os_Getenv(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getenv(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_Geteuid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Geteuid()
		return SkyOk(result)
	}()
}

func Sky_os_Getgid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getgid()
		return SkyOk(result)
	}()
}

func Sky_os_Getpagesize() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getpagesize()
		return SkyOk(result)
	}()
}

func Sky_os_Getpid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getpid()
		return SkyOk(result)
	}()
}

func Sky_os_Getppid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getppid()
		return SkyOk(result)
	}()
}

func Sky_os_Getuid() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.Getuid()
		return SkyOk(result)
	}()
}

func Sky_os_Getwd() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Getwd()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Hostname() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Hostname()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_IsExist(arg0 any) any {
	_arg0 := sky_asError(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.IsExist(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_IsNotExist(arg0 any) any {
	_arg0 := sky_asError(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.IsNotExist(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_IsPathSeparator(arg0 any) any {
	_arg0 := sky_asUint8(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.IsPathSeparator(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_IsPermission(arg0 any) any {
	_arg0 := sky_asError(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.IsPermission(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_IsTimeout(arg0 any) any {
	_arg0 := sky_asError(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.IsTimeout(_arg0)
		return SkyOk(result)
	}()
}

func Sky_os_Lchown(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := sky_asInt(arg2)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Lchown(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Link(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Link(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_LookupEnv(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_r0, _r1 := os.LookupEnv(_arg0)
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_os_Lstat(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Lstat(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Mkdir(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Mkdir(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_MkdirAll(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.MkdirAll(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_MkdirTemp(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.MkdirTemp(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_NewSyscallError(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asError(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.NewSyscallError(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Open(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Open(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_OpenFile(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := func() os.FileMode {
		if v, ok := arg2.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.OpenFile(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_OpenInRoot(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.OpenInRoot(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_OpenRoot(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.OpenRoot(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_ReadDir(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.ReadDir(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_ReadFile(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.ReadFile(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Readlink(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Readlink(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Remove(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Remove(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RemoveAll(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.RemoveAll(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Rename(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Rename(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_SameFile(arg0 any, arg1 any) any {
	_arg0 := func() os.FileInfo {
		if v, ok := arg0.(os.FileInfo); ok {
			return v
		}
		var zero os.FileInfo
		return zero
	}()
	_arg1 := func() os.FileInfo {
		if v, ok := arg1.(os.FileInfo); ok {
			return v
		}
		var zero os.FileInfo
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.SameFile(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_os_Setenv(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Setenv(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_StartProcess(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asStringSlice(arg1)
	_arg2 := func() *os.ProcAttr {
		if arg2 == nil {
			return nil
		}
		return arg2.(*os.ProcAttr)
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.StartProcess(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Stat(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.Stat(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_Symlink(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Symlink(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_TempDir() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := os.TempDir()
		return SkyOk(result)
	}()
}

func Sky_os_Truncate(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt64(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Truncate(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Unsetenv(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.Unsetenv(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_UserCacheDir() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.UserCacheDir()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_UserConfigDir() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.UserConfigDir()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_UserHomeDir() any {

	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := os.UserHomeDir()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_WriteFile(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBytes(arg1)
	_arg2 := func() os.FileMode {
		if v, ok := arg2.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := os.WriteFile(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileChdir(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Chdir()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileChmod(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := func() os.FileMode {
		if v, ok := arg0.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Chmod(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileChown(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt(arg0)
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Chown(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileClose(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Close()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileName(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_os_FileRead(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Read(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileReadAt(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asInt64(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadAt(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileReadDir(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadDir(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileReadFrom(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := func() io.Reader {
		if v, ok := arg0.(io.Reader); ok {
			return v
		}
		var zero io.Reader
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadFrom(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileReaddir(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Readdir(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileReaddirnames(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Readdirnames(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileSeek(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt64(arg0)
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Seek(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileStat(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Stat()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileSync(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Sync()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileSyscallConn(receiver any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.SyscallConn()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileTruncate(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asInt64(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Truncate(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_FileWrite(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Write(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileWriteAt(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asInt64(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteAt(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileWriteString(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteString(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_FileWriteTo(receiver any, arg0 any) any {
	var _receiver *os.File
	if _p, ok := receiver.(*os.File); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.File); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected File")
	}
	_arg0 := func() io.Writer {
		if v, ok := arg0.(io.Writer); ok {
			return v
		}
		var zero io.Writer
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.WriteTo(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_LinkErrorError(receiver any) any {
	var _receiver *os.LinkError
	if _p, ok := receiver.(*os.LinkError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.LinkError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected LinkError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Error()
		return SkyOk(result)
	}()
}

func Sky_os_LinkErrorUnwrap(receiver any) any {
	var _receiver *os.LinkError
	if _p, ok := receiver.(*os.LinkError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.LinkError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected LinkError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Unwrap()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_ProcessKill(receiver any) any {
	var _receiver *os.Process
	if _p, ok := receiver.(*os.Process); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Process); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Process")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Kill()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_ProcessRelease(receiver any) any {
	var _receiver *os.Process
	if _p, ok := receiver.(*os.Process); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Process); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Process")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Release()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_ProcessSignal(receiver any, arg0 any) any {
	var _receiver *os.Process
	if _p, ok := receiver.(*os.Process); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Process); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Process")
	}
	_arg0 := func() os.Signal {
		if v, ok := arg0.(os.Signal); ok {
			return v
		}
		var zero os.Signal
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Signal(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_ProcessWait(receiver any) any {
	var _receiver *os.Process
	if _p, ok := receiver.(*os.Process); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Process); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Process")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Wait()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateExitCode(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ExitCode()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateExited(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Exited()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStatePid(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Pid()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateString(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateSuccess(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Success()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateSys(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Sys()
		return SkyOk(result)
	}()
}

func Sky_os_ProcessStateSysUsage(receiver any) any {
	var _receiver *os.ProcessState
	if _p, ok := receiver.(*os.ProcessState); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.ProcessState); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ProcessState")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.SysUsage()
		return SkyOk(result)
	}()
}

func Sky_os_RootChmod(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Chmod(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootChown(receiver any, arg0 any, arg1 any, arg2 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := sky_asInt(arg2)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Chown(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootClose(receiver any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Close()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootCreate(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Create(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootLchown(receiver any, arg0 any, arg1 any, arg2 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := sky_asInt(arg2)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Lchown(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootLink(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Link(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootLstat(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Lstat(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootMkdir(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Mkdir(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootMkdirAll(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := func() os.FileMode {
		if v, ok := arg1.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.MkdirAll(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootName(receiver any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Name()
		return SkyOk(result)
	}()
}

func Sky_os_RootOpen(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Open(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootOpenFile(receiver any, arg0 any, arg1 any, arg2 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	_arg2 := func() os.FileMode {
		if v, ok := arg2.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.OpenFile(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootOpenRoot(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.OpenRoot(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootReadFile(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.ReadFile(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootReadlink(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Readlink(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootRemove(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Remove(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootRemoveAll(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.RemoveAll(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootRename(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Rename(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootStat(receiver any, arg0 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Stat(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_RootSymlink(receiver any, arg0 any, arg1 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Symlink(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_RootWriteFile(receiver any, arg0 any, arg1 any, arg2 any) any {
	var _receiver *os.Root
	if _p, ok := receiver.(*os.Root); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.Root); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Root")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBytes(arg1)
	_arg2 := func() os.FileMode {
		if v, ok := arg2.(os.FileMode); ok {
			return v
		}
		var zero os.FileMode
		return zero
	}()
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.WriteFile(_arg0, _arg1, _arg2)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_SignalSignal(receiver any) any {
	var _receiver os.Signal
	if _v, ok := receiver.(os.Signal); ok {
		_receiver = _v
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Signal()
		return SkyOk(struct{}{})
	}()
}

func Sky_os_SignalString(receiver any) any {
	var _receiver os.Signal
	if _v, ok := receiver.(os.Signal); ok {
		_receiver = _v
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_os_SyscallErrorError(receiver any) any {
	var _receiver *os.SyscallError
	if _p, ok := receiver.(*os.SyscallError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.SyscallError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected SyscallError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Error()
		return SkyOk(result)
	}()
}

func Sky_os_SyscallErrorTimeout(receiver any) any {
	var _receiver *os.SyscallError
	if _p, ok := receiver.(*os.SyscallError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.SyscallError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected SyscallError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Timeout()
		return SkyOk(result)
	}()
}

func Sky_os_SyscallErrorUnwrap(receiver any) any {
	var _receiver *os.SyscallError
	if _p, ok := receiver.(*os.SyscallError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(os.SyscallError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected SyscallError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Unwrap()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_Args(_ any) any {
	src := os.Args
	result := make([]any, len(src))
	for i, v := range src {
		result[i] = v
	}
	return result
}

func Sky_os_Interrupt(_ any) any {
	return os.Interrupt
}

func Sky_os_Kill(_ any) any {
	return os.Kill
}

func Sky_os_Stderr(_ any) any {
	return os.Stderr
}

func Sky_os_Stdin(_ any) any {
	return os.Stdin
}

func Sky_os_Stdout(_ any) any {
	return os.Stdout
}

func Sky_os_Chtimes(arg0 any, arg1 any, arg2 any) SkyResult {
	_arg0 := arg0.(string)
	_arg1 := arg1.(time.Time)
	_arg2 := arg2.(time.Time)
	err := os.Chtimes(_arg0, _arg1, _arg2)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_CopyFS(arg0 any, arg1 any) SkyResult {
	_arg0 := arg0.(string)
	_arg1 := arg1.(fs.FS)
	err := os.CopyFS(_arg0, _arg1)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_DirFS(arg0 any) fs.FS {
	_arg0 := arg0.(string)
	return os.DirFS(_arg0)
}

func Sky_os_Expand(arg0 any, arg1 any) string {
	_arg0 := arg0.(string)
	_skyFn1 := arg1.(func(any) any)
	_arg1 := func(p0 string) string {
		return _skyFn1(p0).(string)
	}
	return os.Expand(_arg0, _arg1)
}

func Sky_os_Getgroups() SkyResult {
	res, err := os.Getgroups()
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(res)
}

func Sky_os_NewFile(arg0 any, arg1 any) *os.File {
	_arg0 := arg0.(uintptr)
	_arg1 := arg1.(string)
	return os.NewFile(_arg0, _arg1)
}

func Sky_os_Pipe() SkyResult {
	_r0, _r1, err := os.Pipe()
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(SkyTuple2{V0: _r0, V1: _r1})
}

func Sky_os_ErrClosed() any {
	return os.ErrClosed
}

func Sky_os_ErrDeadlineExceeded() any {
	return os.ErrDeadlineExceeded
}

func Sky_os_ErrExist() any {
	return os.ErrExist
}

func Sky_os_ErrInvalid() any {
	return os.ErrInvalid
}

func Sky_os_ErrNoDeadline() any {
	return os.ErrNoDeadline
}

func Sky_os_ErrNoHandle() any {
	return os.ErrNoHandle
}

func Sky_os_ErrNotExist() any {
	return os.ErrNotExist
}

func Sky_os_ErrPermission() any {
	return os.ErrPermission
}

func Sky_os_ErrProcessDone() any {
	return os.ErrProcessDone
}

func Sky_os_DevNull() any {
	return os.DevNull
}

func Sky_os_ModeAppend() any {
	return os.ModeAppend
}

func Sky_os_ModeCharDevice() any {
	return os.ModeCharDevice
}

func Sky_os_ModeDevice() any {
	return os.ModeDevice
}

func Sky_os_ModeDir() any {
	return os.ModeDir
}

func Sky_os_ModeExclusive() any {
	return os.ModeExclusive
}

func Sky_os_ModeIrregular() any {
	return os.ModeIrregular
}

func Sky_os_ModeNamedPipe() any {
	return os.ModeNamedPipe
}

func Sky_os_ModePerm() any {
	return os.ModePerm
}

func Sky_os_ModeSetgid() any {
	return os.ModeSetgid
}

func Sky_os_ModeSetuid() any {
	return os.ModeSetuid
}

func Sky_os_ModeSocket() any {
	return os.ModeSocket
}

func Sky_os_ModeSticky() any {
	return os.ModeSticky
}

func Sky_os_ModeSymlink() any {
	return os.ModeSymlink
}

func Sky_os_ModeTemporary() any {
	return os.ModeTemporary
}

func Sky_os_ModeType() any {
	return os.ModeType
}

func Sky_os_O_APPEND() any {
	return os.O_APPEND
}

func Sky_os_O_CREATE() any {
	return os.O_CREATE
}

func Sky_os_O_EXCL() any {
	return os.O_EXCL
}

func Sky_os_O_RDONLY() any {
	return os.O_RDONLY
}

func Sky_os_O_RDWR() any {
	return os.O_RDWR
}

func Sky_os_O_SYNC() any {
	return os.O_SYNC
}

func Sky_os_O_TRUNC() any {
	return os.O_TRUNC
}

func Sky_os_O_WRONLY() any {
	return os.O_WRONLY
}

func Sky_os_PathListSeparator() any {
	return os.PathListSeparator
}

func Sky_os_PathSeparator() any {
	return os.PathSeparator
}

func Sky_os_SEEK_CUR() any {
	return os.SEEK_CUR
}

func Sky_os_SEEK_END() any {
	return os.SEEK_END
}

func Sky_os_SEEK_SET() any {
	return os.SEEK_SET
}

func Sky_os_FileFd(this any) uintptr {
	var _this *os.File
	if _p, ok := this.(*os.File); ok {
		_this = _p
	} else {
		_v := this.(os.File)
		_this = &_v
	}

	return _this.Fd()
}

func Sky_os_FileSetDeadline(this any, arg0 any) SkyResult {
	var _this *os.File
	if _p, ok := this.(*os.File); ok {
		_this = _p
	} else {
		_v := this.(os.File)
		_this = &_v
	}
	_arg0 := arg0.(time.Time)
	err := _this.SetDeadline(_arg0)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_FileSetReadDeadline(this any, arg0 any) SkyResult {
	var _this *os.File
	if _p, ok := this.(*os.File); ok {
		_this = _p
	} else {
		_v := this.(os.File)
		_this = &_v
	}
	_arg0 := arg0.(time.Time)
	err := _this.SetReadDeadline(_arg0)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_FileSetWriteDeadline(this any, arg0 any) SkyResult {
	var _this *os.File
	if _p, ok := this.(*os.File); ok {
		_this = _p
	} else {
		_v := this.(os.File)
		_this = &_v
	}
	_arg0 := arg0.(time.Time)
	err := _this.SetWriteDeadline(_arg0)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_LinkErrorOp(this any) string {
	var _this *os.LinkError
	if _p, ok := this.(*os.LinkError); ok {
		_this = _p
	} else {
		_v := this.(os.LinkError)
		_this = &_v
	}

	return _this.Op
}

func Sky_os_LinkErrorOld(this any) string {
	var _this *os.LinkError
	if _p, ok := this.(*os.LinkError); ok {
		_this = _p
	} else {
		_v := this.(os.LinkError)
		_this = &_v
	}

	return _this.Old
}

func Sky_os_LinkErrorNew(this any) string {
	var _this *os.LinkError
	if _p, ok := this.(*os.LinkError); ok {
		_this = _p
	} else {
		_v := this.(os.LinkError)
		_this = &_v
	}

	return _this.New
}

func Sky_os_LinkErrorErr(this any) error {
	var _this *os.LinkError
	if _p, ok := this.(*os.LinkError); ok {
		_this = _p
	} else {
		_v := this.(os.LinkError)
		_this = &_v
	}

	return _this.Err
}

func Sky_os_ProcAttrDir(this any) string {
	var _this *os.ProcAttr
	if _p, ok := this.(*os.ProcAttr); ok {
		_this = _p
	} else {
		_v := this.(os.ProcAttr)
		_this = &_v
	}

	return _this.Dir
}

func Sky_os_ProcAttrEnv(this any) any {
	var _this *os.ProcAttr
	if _p, ok := this.(*os.ProcAttr); ok {
		_this = _p
	} else {
		_v := this.(os.ProcAttr)
		_this = &_v
	}

	_val := _this.Env
	_result := make([]any, len(_val))
	for _i, _v := range _val {
		_result[_i] = _v
	}
	return _result
}

func Sky_os_ProcAttrFiles(this any) any {
	var _this *os.ProcAttr
	if _p, ok := this.(*os.ProcAttr); ok {
		_this = _p
	} else {
		_v := this.(os.ProcAttr)
		_this = &_v
	}

	_val := _this.Files
	_result := make([]any, len(_val))
	for _i, _v := range _val {
		_result[_i] = _v
	}
	return _result
}

func Sky_os_ProcAttrSys(this any) *syscall.SysProcAttr {
	var _this *os.ProcAttr
	if _p, ok := this.(*os.ProcAttr); ok {
		_this = _p
	} else {
		_v := this.(os.ProcAttr)
		_this = &_v
	}

	return _this.Sys
}

func Sky_os_ProcessWithHandle(this any, arg0 any) SkyResult {
	var _this *os.Process
	if _p, ok := this.(*os.Process); ok {
		_this = _p
	} else {
		_v := this.(os.Process)
		_this = &_v
	}
	_skyFn0 := arg0.(func(any) any)
	_arg0 := func(p0 uintptr) {
		_skyFn0(p0)
	}
	err := _this.WithHandle(_arg0)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_ProcessPid(this any) int {
	var _this *os.Process
	if _p, ok := this.(*os.Process); ok {
		_this = _p
	} else {
		_v := this.(os.Process)
		_this = &_v
	}

	return _this.Pid
}

func Sky_os_ProcessStateSystemTime(this any) time.Duration {
	var _this *os.ProcessState
	if _p, ok := this.(*os.ProcessState); ok {
		_this = _p
	} else {
		_v := this.(os.ProcessState)
		_this = &_v
	}

	return _this.SystemTime()
}

func Sky_os_ProcessStateUserTime(this any) time.Duration {
	var _this *os.ProcessState
	if _p, ok := this.(*os.ProcessState); ok {
		_this = _p
	} else {
		_v := this.(os.ProcessState)
		_this = &_v
	}

	return _this.UserTime()
}

func Sky_os_RootChtimes(this any, arg0 any, arg1 any, arg2 any) SkyResult {
	var _this *os.Root
	if _p, ok := this.(*os.Root); ok {
		_this = _p
	} else {
		_v := this.(os.Root)
		_this = &_v
	}
	_arg0 := arg0.(string)
	_arg1 := arg1.(time.Time)
	_arg2 := arg2.(time.Time)
	err := _this.Chtimes(_arg0, _arg1, _arg2)
	if err != nil {
		return SkyErr(err)
	}
	return SkyOk(struct{}{})
}

func Sky_os_RootFS(this any) fs.FS {
	var _this *os.Root
	if _p, ok := this.(*os.Root); ok {
		_this = _p
	} else {
		_v := this.(os.Root)
		_this = &_v
	}

	return _this.FS()
}

func Sky_os_SyscallErrorSyscall(this any) string {
	var _this *os.SyscallError
	if _p, ok := this.(*os.SyscallError); ok {
		_this = _p
	} else {
		_v := this.(os.SyscallError)
		_this = &_v
	}

	return _this.Syscall
}

func Sky_os_SyscallErrorErr(this any) error {
	var _this *os.SyscallError
	if _p, ok := this.(*os.SyscallError); ok {
		_this = _p
	} else {
		_v := this.(os.SyscallError)
		_this = &_v
	}

	return _this.Err
}
