package main

import (
	_ffi_fmt "fmt"
	exec "os/exec"
	_ffi_reflect "reflect"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_os_exec_Command(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asStringSlice(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := exec.Command(_arg0, _arg1...)
		return SkyOk(result)
	}()
}

func Sky_os_exec_CommandContext(arg0 any, arg1 any, arg2 any) any {
	_arg0 := sky_asContext(arg0)
	_arg1 := sky_asString(arg1)
	_arg2 := sky_asStringSlice(arg2)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := exec.CommandContext(_arg0, _arg1, _arg2...)
		return SkyOk(result)
	}()
}

func Sky_os_exec_LookPath(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := exec.LookPath(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdCombinedOutput(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.CombinedOutput()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdEnviron(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Environ()
		return SkyOk(result[:])
	}()
}

func Sky_os_exec_CmdOutput(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.Output()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdRun(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Run()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_exec_CmdStart(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Start()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_exec_CmdStderrPipe(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.StderrPipe()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdStdinPipe(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.StdinPipe()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdStdoutPipe(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.StdoutPipe()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdString(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_os_exec_CmdWait(receiver any) any {
	var _receiver *exec.Cmd
	if _p, ok := receiver.(*exec.Cmd); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Cmd); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Cmd")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Wait()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_exec_ErrorError(receiver any) any {
	var _receiver *exec.Error
	if _p, ok := receiver.(*exec.Error); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Error); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Error")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Error()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ErrorUnwrap(receiver any) any {
	var _receiver *exec.Error
	if _p, ok := receiver.(*exec.Error); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.Error); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Error")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.Unwrap()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}

func Sky_os_exec_ExitErrorError(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Error()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorExitCode(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ExitCode()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorExited(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Exited()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorPid(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Pid()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorString(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorSuccess(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Success()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorSys(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Sys()
		return SkyOk(result)
	}()
}

func Sky_os_exec_ExitErrorSysUsage(receiver any) any {
	var _receiver *exec.ExitError
	if _p, ok := receiver.(*exec.ExitError); ok {
		_receiver = _p
	} else if _v, ok := receiver.(exec.ExitError); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected ExitError")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.SysUsage()
		return SkyOk(result)
	}()
}

func Sky_os_exec_FIELD_Cmd_Path(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Path")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Args(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Args")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Env(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Env")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Dir(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Dir")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Stdin(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Stdin")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Stdout(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Stdout")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_Stderr(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Stderr")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_ExtraFiles(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ExtraFiles")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_SysProcAttr(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("SysProcAttr")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}

func Sky_os_exec_FIELD_Cmd_Process(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Process")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}

func Sky_os_exec_FIELD_Cmd_ProcessState(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ProcessState")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}

func Sky_os_exec_FIELD_Cmd_Err(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Err")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Cmd_WaitDelay(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("WaitDelay")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Error_Name(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Name")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_Error_Err(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Err")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}

func Sky_os_exec_FIELD_ExitError_ProcessState(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("ProcessState")
		if f.IsValid() {
			if f.IsNil() {
				return SkyNothing()
			}
			return SkyJust(f.Interface())
		}
	}
	return SkyNothing()
}

func Sky_os_exec_FIELD_ExitError_Stderr(receiver any) any {
	v := _ffi_reflect.ValueOf(receiver)
	for v.Kind() == _ffi_reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() == _ffi_reflect.Struct {
		f := v.FieldByName("Stderr")
		if f.IsValid() {
			return f.Interface()
		}
	}
	return nil
}
