package main

import (
	_ffi_fmt "fmt"
	regexp "regexp"
)

var _ = _ffi_fmt.Sprintf

// Auto-generated by Sky compiler

func Sky_regexp_Compile(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := regexp.Compile(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_CompilePOSIX(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := regexp.CompilePOSIX(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_Match(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asBytes(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := regexp.Match(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_MatchString(arg0 any, arg1 any) any {
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := regexp.MatchString(_arg0, _arg1)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_MustCompile(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := regexp.MustCompile(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_MustCompilePOSIX(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := regexp.MustCompilePOSIX(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_QuoteMeta(arg0 any) any {
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := regexp.QuoteMeta(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpAppendText(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.AppendText(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpCopy(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Copy()
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpFind(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Find(_arg0)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpFindAllString(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.FindAllString(_arg0, _arg1)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpFindString(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.FindString(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpFindStringSubmatch(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.FindStringSubmatch(_arg0)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpLiteralPrefix(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_r0, _r1 := _receiver.LiteralPrefix()
		return SkyOk(SkyTuple2{_r0, _r1})
	}()
}

func Sky_regexp_RegexpLongest(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		_receiver.Longest()
		return SkyOk(struct{}{})
	}()
}

func Sky_regexp_RegexpMarshalText(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result, err := _receiver.MarshalText()
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpMatch(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Match(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpMatchString(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.MatchString(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpNumSubexp(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.NumSubexp()
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpReplaceAll(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asBytes(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ReplaceAll(_arg0, _arg1)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpReplaceAllLiteral(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	_arg1 := sky_asBytes(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ReplaceAllLiteral(_arg0, _arg1)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpReplaceAllLiteralString(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ReplaceAllLiteralString(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpReplaceAllString(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asString(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.ReplaceAllString(_arg0, _arg1)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpSplit(receiver any, arg0 any, arg1 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	_arg1 := sky_asInt(arg1)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.Split(_arg0, _arg1)
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpString(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.String()
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpSubexpIndex(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asString(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.SubexpIndex(_arg0)
		return SkyOk(result)
	}()
}

func Sky_regexp_RegexpSubexpNames(receiver any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		result := _receiver.SubexpNames()
		return SkyOk(result[:])
	}()
}

func Sky_regexp_RegexpUnmarshalText(receiver any, arg0 any) any {
	var _receiver *regexp.Regexp
	if _p, ok := receiver.(*regexp.Regexp); ok {
		_receiver = _p
	} else if _v, ok := receiver.(regexp.Regexp); ok {
		_receiver = &_v
	}
	if _receiver == nil {
		return SkyErr("nil receiver: expected Regexp")
	}
	_arg0 := sky_asBytes(arg0)
	return func() (__ret any) {
		defer func() {
			if r := recover(); r != nil {
				__ret = SkyErr(_ffi_fmt.Sprintf("FFI panic: %v", r))
			}
		}()
		err := _receiver.UnmarshalText(_arg0)
		if err != nil {
			return SkyErr(err.Error())
		}
		return SkyOk(struct{}{})
	}()
}
